[tool.poetry]
name = "sentinel2-downloader"
version = "0.3.1"
description = ""
authors = ["wwdegroot <wouter.w.de.groot@gmail.com>"]
readme = "README.md"
packages = [{include = "st2dl"}]

[tool.poetry.dependencies]
python = "^3.12"
httpx = "^0.28.1"
python-dotenv = "^1.0.0"
orjson = "^3.10.18"
rich = "^14.0.0"
click = "^8.2.1"
msgspec = "^0.19.0"
asyncclick = "^8.1.8"


[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
ruff = "^0.12.0"
pre-commit = "^4.2.0"
pytest-httpx = "^0.35.0"
pytest-asyncio = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
